package com.adolfosc.ui;

import com.adolfosc.analizadores.ErrorSintaxis;
import com.adolfosc.analizadores.colorear.ColorearLexer;
import com.adolfosc.analizadores.service.CompilarCodigo;
import com.adolfosc.conexion_socket.Servidor;
import com.adolfosc.controladores.ControlDuracion;
import com.adolfosc.modelo.music.Lista;
import com.adolfosc.modelo.music.Nota;
import com.adolfosc.service.CargarListaService;
import com.adolfosc.service.CargarPistaService;
import com.adolfosc.ui.resource.ActivaProgressBarr;
import com.adolfosc.ui.resource.FileManager;
import com.adolfosc.ui.resource.InsetGrafic;
import com.adolfosc.ui.resource.NumeroLinea;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Utilities;

/**
 *
 * @author hectoradolfo
 */
public class RecordMusicUi extends javax.swing.JFrame {

    //declaracion de variables
    private NumeroLinea numLinea;
    private NumeroLinea numLineaLista;
    private InsetGrafic insert;
    private FileManager file;
    private String pathActual, pathNuevo;
    private int estadoProgres = 0;
    private ActivaProgressBarr activarPb;

    private List<Nota> notasPistaRep;
    private List<String> mensajes;
    private int durPista = 0;
    private int caretAct;
    private boolean codigoCargado;
    private List<String> pistasEnLista;
    private Lista lista;
    private List<ErrorSintaxis> errores;
    private CargarPistaService cargaPistaService;
    private CargarListaService cargarListaServie;
    private ControlDuracion controlD;
    private Servidor servidor;

    /**
     * Creates new form MusicUi
     */
    public RecordMusicUi() {
        initComponents();
        setLocationRelativeTo(null);
        this.pathNuevo = "";
        this.pathActual = "";
        this.codigoCargado = false;
        this.file = new FileManager();
        this.activarPb = new ActivaProgressBarr(0, 0, 0);
        this.numLinea = new NumeroLinea(jtpEditPista);
        this.jScrollPane1.setRowHeaderView(numLinea);
        this.errores = new ArrayList<>();
        this.notasPistaRep = new ArrayList<>();
        this.pistasEnLista = new ArrayList<>();
        this.mensajes = new ArrayList<>();
        this.cargaPistaService = new CargarPistaService();
        this.cargarListaServie = new CargarListaService();

        numLineaLista = new NumeroLinea(jtpEditLista);
        jScrollPane3.setRowHeaderView(numLineaLista);

        ImageIcon open = new ImageIcon("src/main/java/com/adolfosc/resource/imagen/play.png");
        Icon iconOpen = new ImageIcon(open.getImage().getScaledInstance(btnPlay.getWidth(),
                btnPlay.getHeight(), Image.SCALE_DEFAULT));
        btnPlay.setIcon(iconOpen);
        this.repaint();
        /*icon para el boton stop*/
        ImageIcon save = new ImageIcon("src/main/java/com/adolfosc/resource/imagen/stop.png");
        Icon iconSave = new ImageIcon(save.getImage().getScaledInstance(btnStop.getWidth(),
                btnStop.getHeight(), Image.SCALE_DEFAULT));
        btnStop.setIcon(iconSave);
        this.repaint();

        insert = new InsetGrafic(jpGrafica);

        obtenerLineColumnEditor(jtpEditPista, jlbLineaPista, jlbColumnaPista);
        obtenerLineColumnEditor(jtpEditLista, jlbLineaLista, jlbColumnaLista);

        //cargar listas de reproduccion y pistas
        this.cargaPistaService.cargarPistas(this.jtableListaPista);
        this.cargarListaServie.cargarListas(jlistListaReproduccion);
        
        //iniciar servidor que respondera al cliente
        this.servidor = new Servidor();
        this.servidor.iniciarServidor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpEditor = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlbNombreListaSeleccionado = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtableListaPista = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jlistListaPista = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        jlistListaReproduccion = new javax.swing.JList<>();
        btnReproducirPista = new javax.swing.JButton();
        btnModificarPista = new javax.swing.JButton();
        btnEliminarPista = new javax.swing.JButton();
        btnReproducirLista = new javax.swing.JButton();
        btnSeleccionarLista = new javax.swing.JButton();
        btnEliminarLista = new javax.swing.JButton();
        btnModificarLista = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtOuputPista = new javax.swing.JTextArea();
        jlbLineaPista = new javax.swing.JLabel();
        jlbColumnaPista = new javax.swing.JLabel();
        btnCompilarPista = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpEditPista = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtxtOuputLista = new javax.swing.JTextArea();
        jlbLineaLista = new javax.swing.JLabel();
        jlbColumnaLista = new javax.swing.JLabel();
        btnCompilarLista = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtpEditLista = new javax.swing.JTextPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jpGrafica = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        btnStop = new javax.swing.JButton();
        jlbInicioPista = new javax.swing.JLabel();
        jlbFinDuracionPista = new javax.swing.JLabel();
        jlbNombrePistaReproducir = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        jmOpenFile = new javax.swing.JMenuItem();
        jmiNuevo = new javax.swing.JMenuItem();
        mItemSave = new javax.swing.JMenuItem();
        jmItemSalir = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        munuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Music Record Compi 2 2021");

        jLabel5.setText("Lista de Pistas");

        jLabel6.setText("Listas de reproducción");

        jLabel7.setText("Pistas en la lista de reproducción");

        jlbNombreListaSeleccionado.setText("  ");

        jtableListaPista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Duración"
            }
        ));
        jScrollPane6.setViewportView(jtableListaPista);

        jScrollPane10.setViewportView(jlistListaPista);

        jScrollPane11.setViewportView(jlistListaReproduccion);

        btnReproducirPista.setBackground(new java.awt.Color(134, 231, 196));
        btnReproducirPista.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        btnReproducirPista.setText("Reproducir");
        btnReproducirPista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReproducirPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproducirPistaActionPerformed(evt);
            }
        });

        btnModificarPista.setBackground(new java.awt.Color(134, 231, 196));
        btnModificarPista.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        btnModificarPista.setText("Modificar");
        btnModificarPista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificarPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPistaActionPerformed(evt);
            }
        });

        btnEliminarPista.setBackground(new java.awt.Color(134, 231, 196));
        btnEliminarPista.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        btnEliminarPista.setText("Eliminar");
        btnEliminarPista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPistaActionPerformed(evt);
            }
        });

        btnReproducirLista.setBackground(new java.awt.Color(134, 231, 196));
        btnReproducirLista.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        btnReproducirLista.setText("Reproducir Lista");
        btnReproducirLista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReproducirLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproducirListaActionPerformed(evt);
            }
        });

        btnSeleccionarLista.setBackground(new java.awt.Color(134, 231, 196));
        btnSeleccionarLista.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        btnSeleccionarLista.setText("Seleccionar");
        btnSeleccionarLista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSeleccionarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarListaActionPerformed(evt);
            }
        });

        btnEliminarLista.setBackground(new java.awt.Color(134, 231, 196));
        btnEliminarLista.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        btnEliminarLista.setText("Eliminar");
        btnEliminarLista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarListaActionPerformed(evt);
            }
        });

        btnModificarLista.setBackground(new java.awt.Color(134, 231, 196));
        btnModificarLista.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        btnModificarLista.setText("Modificar");
        btnModificarLista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReproducirPista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarPista)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarPista))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jlbNombreListaSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReproducirLista, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSeleccionarLista)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarLista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminarLista)
                                .addGap(62, 62, 62))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSeleccionarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbNombreListaSeleccionado)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReproducirPista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarPista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarPista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReproducirLista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jtpEditor.addTab("Biblioteca", jPanel1);

        jtxtOuputPista.setColumns(20);
        jtxtOuputPista.setForeground(new java.awt.Color(255, 255, 255));
        jtxtOuputPista.setRows(5);
        jtxtOuputPista.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        jtxtOuputPista.setEnabled(false);
        jtxtOuputPista.setOpaque(false);
        jScrollPane2.setViewportView(jtxtOuputPista);

        jlbLineaPista.setText("Linea:  1");

        jlbColumnaPista.setText("Columna:  1");

        btnCompilarPista.setBackground(new java.awt.Color(134, 231, 196));
        btnCompilarPista.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        btnCompilarPista.setText("Compilar");
        btnCompilarPista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCompilarPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompilarPistaActionPerformed(evt);
            }
        });

        jLabel1.setText("Salida:");

        jLabel2.setText("Editor Codigo:");

        jScrollPane4.setViewportView(jTextPane1);

        jtpEditPista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtpEditPistaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jtpEditPista);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnCompilarPista, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addComponent(jlbLineaPista, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbColumnaPista, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlbLineaPista)
                                .addComponent(jlbColumnaPista))
                            .addComponent(btnCompilarPista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jtpEditor.addTab("Crear Pista", jPanel2);

        jtxtOuputLista.setColumns(20);
        jtxtOuputLista.setRows(5);
        jtxtOuputLista.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        jtxtOuputLista.setEnabled(false);
        jScrollPane5.setViewportView(jtxtOuputLista);

        jlbLineaLista.setText("Linea:  1");

        jlbColumnaLista.setText("Columna:  1");

        btnCompilarLista.setBackground(new java.awt.Color(134, 231, 196));
        btnCompilarLista.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        btnCompilarLista.setText("Compilar");
        btnCompilarLista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCompilarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompilarListaActionPerformed(evt);
            }
        });

        jLabel3.setText("Salida:");

        jLabel4.setText("Editor Codigo:");

        jtpEditLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtpEditListaKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(jtpEditLista);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnCompilarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addComponent(jlbLineaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbColumnaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbLineaLista)
                        .addComponent(jlbColumnaLista))
                    .addComponent(btnCompilarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jtpEditor.addTab("Crear Lista Reproduccion", jPanel5);

        javax.swing.GroupLayout jpGraficaLayout = new javax.swing.GroupLayout(jpGrafica);
        jpGrafica.setLayout(jpGraficaLayout);
        jpGraficaLayout.setHorizontalGroup(
            jpGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpGraficaLayout.setVerticalGroup(
            jpGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        btnPlay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        progressBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        progressBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        jlbInicioPista.setText("0");

        jlbNombrePistaReproducir.setText("Pista:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbNombrePistaReproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbInicioPista, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbFinDuracionPista, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jlbNombrePistaReproducir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbInicioPista)
                    .addComponent(jlbFinDuracionPista, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Reproductor Musica", jPanel4);

        menuFile.setText("Archivo");

        jmOpenFile.setText("Abrir archivo");
        jmOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmOpenFileActionPerformed(evt);
            }
        });
        menuFile.add(jmOpenFile);

        jmiNuevo.setText("Nuevo");
        jmiNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoActionPerformed(evt);
            }
        });
        menuFile.add(jmiNuevo);

        mItemSave.setText("Guardar");
        mItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSaveActionPerformed(evt);
            }
        });
        menuFile.add(mItemSave);

        jmItemSalir.setText("Salir");
        jmItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemSalirActionPerformed(evt);
            }
        });
        menuFile.add(jmItemSalir);

        jMenuBar1.add(menuFile);

        menuReportes.setText("Reportes");
        jMenuBar1.add(menuReportes);

        munuAyuda.setText("Ayuda");
        jMenuBar1.add(munuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpEditor)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpEditor)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompilarPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarPistaActionPerformed
        this.jtxtOuputPista.setText("");
        CompilarCodigo compilar = new CompilarCodigo();
        compilar.compilar(this.jtpEditPista.getText(), this.lista, this.errores, this.codigoCargado, this.notasPistaRep,
                this.mensajes, this.jtxtOuputPista, false);
        this.cargaPistaService.cargarPistas(this.jtableListaPista);        
    }//GEN-LAST:event_btnCompilarPistaActionPerformed

    private void btnCompilarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarListaActionPerformed
        this.jtxtOuputLista.setText("");
        CompilarCodigo compilar = new CompilarCodigo();
        compilar.compilar(this.jtpEditLista.getText(), this.lista, this.errores, this.codigoCargado, this.notasPistaRep,
                this.mensajes, this.jtxtOuputLista, true);
        this.cargarListaServie.cargarListas(jlistListaReproduccion);
    }//GEN-LAST:event_btnCompilarListaActionPerformed

    private void jmOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmOpenFileActionPerformed
        int a = jtpEditor.getSelectedIndex();

        switch (a) {
            case 1:
                JFileChooser fileChooser = new JFileChooser();
                file.openFile(fileChooser, pathActual, jtpEditPista);
                if (file.isOpcion()) {
                    pathActual = file.getNuevoPath();
                    JOptionPane.showMessageDialog(null, "Archivo leido correctamente ",
                            "Mensaje Abrir Archivo", 1);
                }
                break;
            case 2:
                JFileChooser fileChooser1 = new JFileChooser();
                file.openFile(fileChooser1, pathNuevo, jtpEditPista/*jtpEditLista*/);
                if (file.isOpcion()) {
                    pathNuevo = file.getNuevoPath();
                    JOptionPane.showMessageDialog(null, "Archivo leido correctamente ",
                            "Mensaje Abrir Archivo", 1);
                }
                break;
            default:
                JOptionPane.showMessageDialog(this, "Tienes que seleccionar "
                        + "primero \nlo que quieres crear (pista o lista de "
                        + "reproduccion) \n !!", "Error en el abrir archivo", 3);
                break;
        }

    }//GEN-LAST:event_jmOpenFileActionPerformed

    private void mItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSaveActionPerformed
        int a = jtpEditor.getSelectedIndex();

        switch (a) {
            case 1:
                if (!this.pathActual.equals("")) {
                    file.saveChangedFile(pathActual, jtpEditPista.getText());
                    JOptionPane.showMessageDialog(null, "Archivo Guardado ", "Mensaje Guardado", 1);
                } else {

                    pathActual = file.saveFile(jtpEditPista.getText());
                    if (!pathActual.equals("")) {
                        JOptionPane.showMessageDialog(null, "Archivo Guardado ", "Mensaje Guardado", 1);

                    } else {
                        JOptionPane.showMessageDialog(null, "No se guardo nada ", "Mensaje Guardado", 1);
                    }
                }
                break;
            case 2:
                if (!this.pathNuevo.equals("")) {
                    file.saveChangedFile(pathNuevo, jtpEditLista.getText());
                    JOptionPane.showMessageDialog(null, "Archivo Guardado ", "Mensaje Guardado", 1);
                } else {

                    pathNuevo = file.saveFile(jtpEditLista.getText());
                    if (!pathNuevo.equals("")) {
                        JOptionPane.showMessageDialog(null, "Archivo Guardado ", "Mensaje Guardado", 1);

                    } else {
                        JOptionPane.showMessageDialog(null, "No se guardo nada ", "Mensaje Guardado", 1);
                    }
                }
                break;
            default:
                JOptionPane.showMessageDialog(this, "Tienes que seleccionar "
                        + "primero \nlo que quieres crear (pista o lista de "
                        + "reproduccion) \n !!", "Error en el abrir archivo", 3);
                break;
        }

    }//GEN-LAST:event_mItemSaveActionPerformed

    private void jmItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmItemSalirActionPerformed

    
    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        
        if (progressBar.getValue() == 0) {
            estadoProgres = 0;
        }
        switch (estadoProgres) {
            case 0:
                activarPb.setMin(0);
                activarPb.setMax(this.durPista);
                activarPb.setOpcion(0);
                activarPb.startProgress(progressBar, btnPlay, this.notasPistaRep);
                estadoProgres = 1;
                activarPb.setOpcion(1);
                break;
            case 1:
                activarPb.startProgress(progressBar, btnPlay, this.notasPistaRep);
                estadoProgres = 2;
                activarPb.setOpcion(2);
                break;
            default:
                activarPb.startProgress(progressBar, btnPlay, this.notasPistaRep);
                estadoProgres = 1;
                activarPb.setOpcion(1);
                break;
        }           
    }//GEN-LAST:event_btnPlayActionPerformed
    
    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        activarPb.setOpcion(3);
        activarPb.startProgress(progressBar, btnPlay, this.notasPistaRep);
        estadoProgres = 0;
        activarPb.setOpcion(0);
    }//GEN-LAST:event_btnStopActionPerformed

    private void jtpEditListaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpEditListaKeyTyped
        int caretPos = jtpEditLista.getCaretPosition();
        escanear(jtpEditLista);
        jtpEditLista.setCaretPosition(caretPos);
    }//GEN-LAST:event_jtpEditListaKeyTyped

    private void jtpEditPistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpEditPistaKeyTyped
        int caretPos = jtpEditPista.getCaretPosition();
        escanear(jtpEditPista);
        jtpEditPista.setCaretPosition(caretPos);
    }//GEN-LAST:event_jtpEditPistaKeyTyped

    private void btnReproducirPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproducirPistaActionPerformed
        //Reproducir : traer la pista seleccionada y transformarla en notas
        try {
            DefaultTableModel tm = (DefaultTableModel) this.jtableListaPista.getModel();
            int rowIndex = this.jtableListaPista.getSelectedRow();
            String cancion = String.valueOf(tm.getValueAt(rowIndex, 0));
            this.controlD = this.cargaPistaService.getSeleccionado(cancion, this.notasPistaRep,
                    this.durPista);
            System.out.println("cargando archivo para reproducir " + this.controlD.getNotas().size());
            this.notasPistaRep = this.controlD.getNotas();
            int duracion = this.controlD.getDuracion();
            double resultadoDouble = (double) duracion / 1000;

            // 
            this.durPista = (int) Math.round(resultadoDouble);
            System.out.println("--->" + this.durPista);

            if (this.controlD != null) {
                System.out.println("hola mundo");
                this.jlbFinDuracionPista.setText(String.valueOf(this.durPista));
                this.jlbNombrePistaReproducir.setText(cancion);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnReproducirPistaActionPerformed

    private void btnModificarPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPistaActionPerformed
        this.codigoCargado = this.cargaPistaService.cargarPistaParaModificar(this.jtableListaPista, this.codigoCargado, this.jtpEditPista);
    }//GEN-LAST:event_btnModificarPistaActionPerformed

    private void btnEliminarPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPistaActionPerformed
        //Eliminar pista seleccionada
        if (JOptionPane.showConfirmDialog(rootPane, "Se eliminará la pista, ¿desea continuar?",
                "Eliminar Pista", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.cargaPistaService.eliminarPista(jtableListaPista);
        }
    }//GEN-LAST:event_btnEliminarPistaActionPerformed

    private void btnReproducirListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproducirListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReproducirListaActionPerformed

    private void btnSeleccionarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarListaActionPerformed
        this.cargarListaServie.verPistasDeLista(jlistListaReproduccion, pistasEnLista,
                jlistListaPista, this.jlbNombreListaSeleccionado);
    }//GEN-LAST:event_btnSeleccionarListaActionPerformed

    private void btnEliminarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarListaActionPerformed
        //Eliminar lista
        if (JOptionPane.showConfirmDialog(rootPane, "Se eliminará la lista, ¿desea continuar?",
                "Eliminar Lista", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.cargarListaServie.eliminarLista(jlistListaReproduccion);
        }
    }//GEN-LAST:event_btnEliminarListaActionPerformed

    private void btnModificarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarListaActionPerformed
        this.codigoCargado = this.cargarListaServie.cargarListaParaModificar(this.jlistListaReproduccion, this.codigoCargado, this.jtpEditLista);
    }//GEN-LAST:event_btnModificarListaActionPerformed

    private void jmiNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoActionPerformed
        // TODO add your handling code here:
        this.jtpEditLista.setText("");
        this.jtpEditPista.setText("");
        this.jtxtOuputLista.setText("");
        this.jtxtOuputPista.setText("");
        this.codigoCargado = false;
    }//GEN-LAST:event_jmiNuevoActionPerformed

    private void escanear(JTextPane jTextPane) {
        try {
            ColorearLexer lex = new ColorearLexer(new BufferedReader(new StringReader(jTextPane.getText())));
            lex.pintar.darEstilo(jTextPane.getText());
            jTextPane.setDocument(lex.pintar.caja2.getDocument());
            lex.scanear();
        } catch (Exception e) {

        }
    }

    private void obtenerLineColumnEditor(JTextPane jTextPane, JLabel line, JLabel column) {
        jTextPane.addCaretListener(new CaretListener() {
            public void caretUpdate(CaretEvent e) {
                try {
                    int caretPos = jTextPane.getCaretPosition();
                    int row = (caretPos == 0) ? 1 : 0;
                    for (int offset = caretPos; offset > 0;) {
                        offset = Utilities.getRowStart(jTextPane, offset) - 1;
                        row++;
                    }
                    int offset = Utilities.getRowStart(jTextPane, caretPos);
                    int col = caretPos - offset + 1;
                    line.setText(String.valueOf("Línea: " + row));
                    column.setText(String.valueOf(" Columna: " + col));
                } catch (Exception exc) {
                    System.out.println(exc);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompilarLista;
    private javax.swing.JButton btnCompilarPista;
    private javax.swing.JButton btnEliminarLista;
    private javax.swing.JButton btnEliminarPista;
    private javax.swing.JButton btnModificarLista;
    private javax.swing.JButton btnModificarPista;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnReproducirLista;
    private javax.swing.JButton btnReproducirPista;
    private javax.swing.JButton btnSeleccionarLista;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel jlbColumnaLista;
    private javax.swing.JLabel jlbColumnaPista;
    private javax.swing.JLabel jlbFinDuracionPista;
    private javax.swing.JLabel jlbInicioPista;
    private javax.swing.JLabel jlbLineaLista;
    private javax.swing.JLabel jlbLineaPista;
    private javax.swing.JLabel jlbNombreListaSeleccionado;
    private javax.swing.JLabel jlbNombrePistaReproducir;
    private javax.swing.JList<String> jlistListaPista;
    private javax.swing.JList<String> jlistListaReproduccion;
    private javax.swing.JMenuItem jmItemSalir;
    private javax.swing.JMenuItem jmOpenFile;
    private javax.swing.JMenuItem jmiNuevo;
    private javax.swing.JPanel jpGrafica;
    private javax.swing.JTable jtableListaPista;
    private javax.swing.JTextPane jtpEditLista;
    private javax.swing.JTextPane jtpEditPista;
    private javax.swing.JTabbedPane jtpEditor;
    private javax.swing.JTextArea jtxtOuputLista;
    private javax.swing.JTextArea jtxtOuputPista;
    private javax.swing.JMenuItem mItemSave;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu munuAyuda;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
