package com.adolfosc.ui;

import com.adolfosc.analizadores.compilador.*;
import com.adolfosc.ui.resource.ActivaProgressBarr;
import com.adolfosc.ui.resource.FileManager;
import com.adolfosc.ui.resource.InsetGrafic;
import com.adolfosc.ui.resource.NumeroLinea;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.text.BadLocationException;

/**
 *
 * @author hectoradolfo
 */
public class RecordMusicUi extends javax.swing.JFrame {

    //declaracion de variables
    private NumeroLinea numLinea;
    private NumeroLinea numLineaLista;
    private InsetGrafic insert;
    private FileManager file;
    private String pathActual, pathNuevo;
    private int estadoProgres = 0;
    private ActivaProgressBarr activarPb;

    /**
     * Creates new form MusicUi
     */
    public RecordMusicUi() {
        initComponents();
        setLocationRelativeTo(null);
        this.pathNuevo = "";
        this.pathActual = "";
        this.file = new FileManager();
        this.activarPb = new ActivaProgressBarr(0, 0, 0);
        numLinea = new NumeroLinea(jtpEditPista);
        jScrollPane1.setRowHeaderView(numLinea);

        numLineaLista = new NumeroLinea(jtpEditLista);
        jScrollPane3.setRowHeaderView(numLineaLista);

        ImageIcon open = new ImageIcon("src/main/java/com/adolfosc/resource/imagen/play.png");
        Icon iconOpen = new ImageIcon(open.getImage().getScaledInstance(btnPlay.getWidth(),
                btnPlay.getHeight(), Image.SCALE_DEFAULT));
        btnPlay.setIcon(iconOpen);
        this.repaint();
        /*icon para el boton stop*/
        ImageIcon save = new ImageIcon("src/main/java/com/adolfosc/resource/imagen/stop.png");
        Icon iconSave = new ImageIcon(save.getImage().getScaledInstance(btnStop.getWidth(),
                btnStop.getHeight(), Image.SCALE_DEFAULT));
        btnStop.setIcon(iconSave);
        this.repaint();

        insert = new InsetGrafic(jpGrafica);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpEditor = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtOuputPista = new javax.swing.JTextArea();
        jlbLineaPista = new javax.swing.JLabel();
        jlbColumnaPista = new javax.swing.JLabel();
        btnCompilarPista = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpEditPista = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtxtOuputLista = new javax.swing.JTextArea();
        jlbLineaLista = new javax.swing.JLabel();
        jlbColumnaLista = new javax.swing.JLabel();
        btnCompilarLista = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtpEditLista = new javax.swing.JTextArea();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jpGrafica = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        btnStop = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        jmOpenFile = new javax.swing.JMenuItem();
        mItemSave = new javax.swing.JMenuItem();
        jmItemSalir = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        munuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Music Record Compi 2 2021");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        jtpEditor.addTab("Biblioteca", jPanel1);

        jtxtOuputPista.setColumns(20);
        jtxtOuputPista.setRows(5);
        jtxtOuputPista.setEnabled(false);
        jScrollPane2.setViewportView(jtxtOuputPista);

        jlbLineaPista.setText("Linea:  1");

        jlbColumnaPista.setText("Columna:  1");

        btnCompilarPista.setBackground(new java.awt.Color(134, 231, 196));
        btnCompilarPista.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        btnCompilarPista.setText("Compilar");
        btnCompilarPista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCompilarPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompilarPistaActionPerformed(evt);
            }
        });

        jLabel1.setText("Salida:");

        jLabel2.setText("Editor Codigo:");

        jtpEditPista.setColumns(20);
        jtpEditPista.setRows(5);
        jtpEditPista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtpEditPistaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtpEditPista);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnCompilarPista, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addComponent(jlbLineaPista, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbColumnaPista, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbLineaPista)
                        .addComponent(jlbColumnaPista))
                    .addComponent(btnCompilarPista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jtpEditor.addTab("Crear Pista", jPanel2);

        jtxtOuputLista.setColumns(20);
        jtxtOuputLista.setRows(5);
        jtxtOuputLista.setEnabled(false);
        jScrollPane5.setViewportView(jtxtOuputLista);

        jlbLineaLista.setText("Linea:  1");

        jlbColumnaLista.setText("Columna:  1");

        btnCompilarLista.setBackground(new java.awt.Color(134, 231, 196));
        btnCompilarLista.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        btnCompilarLista.setText("Compilar");
        btnCompilarLista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCompilarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompilarListaActionPerformed(evt);
            }
        });

        jLabel3.setText("Salida:");

        jLabel4.setText("Editor Codigo:");

        jtpEditLista.setColumns(20);
        jtpEditLista.setRows(5);
        jtpEditLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtpEditListaKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jtpEditLista);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnCompilarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addComponent(jlbLineaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbColumnaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbLineaLista)
                        .addComponent(jlbColumnaLista))
                    .addComponent(btnCompilarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jtpEditor.addTab("Crear Lista Reproduccion", jPanel5);

        javax.swing.GroupLayout jpGraficaLayout = new javax.swing.GroupLayout(jpGrafica);
        jpGrafica.setLayout(jpGraficaLayout);
        jpGraficaLayout.setHorizontalGroup(
            jpGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpGraficaLayout.setVerticalGroup(
            jpGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        btnPlay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        progressBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        progressBar.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );

        jTabbedPane2.addTab("Reproductor Musica", jPanel4);

        menuFile.setText("File");

        jmOpenFile.setText("Open File");
        jmOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmOpenFileActionPerformed(evt);
            }
        });
        menuFile.add(jmOpenFile);

        mItemSave.setText("Save");
        mItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSaveActionPerformed(evt);
            }
        });
        menuFile.add(mItemSave);

        jmItemSalir.setText("Exit");
        jmItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemSalirActionPerformed(evt);
            }
        });
        menuFile.add(jmItemSalir);

        jMenuBar1.add(menuFile);

        menuReportes.setText("Reportes");
        jMenuBar1.add(menuReportes);

        munuAyuda.setText("Ayuda");
        jMenuBar1.add(munuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpEditor)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpEditor)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompilarPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarPistaActionPerformed
        // TODO add your handling code here:
        //CompilaCodePista compilar = new CompilaCodePista();
        //compilar.parsearCodigo(jtpEditPista);
    }//GEN-LAST:event_btnCompilarPistaActionPerformed

    private void btnCompilarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCompilarListaActionPerformed

    private void jmOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmOpenFileActionPerformed
        int a = jtpEditor.getSelectedIndex();

        switch (a) {
            case 1:
                JFileChooser fileChooser = new JFileChooser();
                file.openFile(fileChooser, pathActual, jtpEditPista);
                if (file.isOpcion()) {
                    pathActual = file.getNuevoPath();
                    JOptionPane.showMessageDialog(null, "Archivo leido correctamente ",
                            "Mensaje Abrir Archivo", 1);
                }
                break;
            case 2:
                JFileChooser fileChooser1 = new JFileChooser();
                file.openFile(fileChooser1, pathNuevo, jtpEditLista);
                if (file.isOpcion()) {
                    pathNuevo = file.getNuevoPath();
                    JOptionPane.showMessageDialog(null, "Archivo leido correctamente ",
                            "Mensaje Abrir Archivo", 1);
                }
                break;
            default:
                JOptionPane.showMessageDialog(this, "Tienes que seleccionar "
                        + "primero \nlo que quieres crear (pista o lista de "
                        + "reproduccion) \n !!", "Error en el abrir archivo", 3);
                break;
        }

    }//GEN-LAST:event_jmOpenFileActionPerformed

    private void mItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSaveActionPerformed
        int a = jtpEditor.getSelectedIndex();

        switch (a) {
            case 1:
                if (!this.pathActual.equals("")) {
                    file.saveChangedFile(pathActual, jtpEditPista.getText());
                    JOptionPane.showMessageDialog(null, "Archivo Guardado ", "Mensaje Guardado", 1);
                } else {

                    pathActual = file.saveFile(jtpEditPista.getText());
                    if (!pathActual.equals("")) {
                        JOptionPane.showMessageDialog(null, "Archivo Guardado ", "Mensaje Guardado", 1);

                    } else {
                        JOptionPane.showMessageDialog(null, "No se guardo nada ", "Mensaje Guardado", 1);
                    }
                }
                break;
            case 2:
                if (!this.pathNuevo.equals("")) {
                    file.saveChangedFile(pathNuevo, jtpEditLista.getText());
                    JOptionPane.showMessageDialog(null, "Archivo Guardado ", "Mensaje Guardado", 1);
                } else {

                    pathNuevo = file.saveFile(jtpEditLista.getText());
                    if (!pathNuevo.equals("")) {
                        JOptionPane.showMessageDialog(null, "Archivo Guardado ", "Mensaje Guardado", 1);

                    } else {
                        JOptionPane.showMessageDialog(null, "No se guardo nada ", "Mensaje Guardado", 1);
                    }
                }
                break;
            default:
                JOptionPane.showMessageDialog(this, "Tienes que seleccionar "
                        + "primero \nlo que quieres crear (pista o lista de "
                        + "reproduccion) \n !!", "Error en el abrir archivo", 3);
                break;
        }

    }//GEN-LAST:event_mItemSaveActionPerformed

    private void jmItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmItemSalirActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        if (progressBar.getValue() == 0) {
            estadoProgres = 0;
        }
        
        switch (estadoProgres) {
            case 0:
                activarPb.setMin(1);
                activarPb.setMax(20);
                activarPb.setOpcion(0);
                activarPb.startProgress(progressBar, btnPlay);
                estadoProgres = 1;
                activarPb.setOpcion(1);
                break;
            case 1:
                activarPb.startProgress(progressBar, btnPlay);
                estadoProgres = 2;
                activarPb.setOpcion(2);
                break;
            default:
                activarPb.startProgress(progressBar, btnPlay);
                estadoProgres = 1;
                activarPb.setOpcion(1);
                break;
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        activarPb.setOpcion(3);
        activarPb.startProgress(progressBar, btnPlay);
        estadoProgres = 0;
        activarPb.setOpcion(0);
    }//GEN-LAST:event_btnStopActionPerformed

    private void jtpEditPistaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpEditPistaKeyPressed
        jtpEditPista.addCaretListener(new CaretListener() {
            public void caretUpdate(CaretEvent e) {
                int pos = e.getDot();
                try {
                    int row = jtpEditPista.getLineOfOffset(pos) + 1;
                    int col = pos - jtpEditPista.getLineStartOffset(row - 1) + 1;
                    jlbLineaPista.setText("Línea: " + row);
                    jlbColumnaPista.setText(" Columna: " + col);
                } catch (BadLocationException exc) {
                    System.out.println(exc);
                }
            }
        });
    }//GEN-LAST:event_jtpEditPistaKeyPressed

    private void jtpEditListaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpEditListaKeyPressed
        jtpEditLista.addCaretListener(new CaretListener() {
            public void caretUpdate(CaretEvent e) {
                int posis = e.getDot();
                try {
                    int row = jtpEditLista.getLineOfOffset(posis) + 1;
                    int col = posis - jtpEditLista.getLineStartOffset(row - 1) + 1;
                    jlbLineaLista.setText("Línea: " + row);
                    jlbColumnaLista.setText(" Columna: " + col);
                } catch (BadLocationException exc) {
                    System.out.println(exc);
                }
            }
        });
    }//GEN-LAST:event_jtpEditListaKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompilarLista;
    private javax.swing.JButton btnCompilarPista;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel jlbColumnaLista;
    private javax.swing.JLabel jlbColumnaPista;
    private javax.swing.JLabel jlbLineaLista;
    private javax.swing.JLabel jlbLineaPista;
    private javax.swing.JMenuItem jmItemSalir;
    private javax.swing.JMenuItem jmOpenFile;
    private javax.swing.JPanel jpGrafica;
    private javax.swing.JTextArea jtpEditLista;
    private javax.swing.JTextArea jtpEditPista;
    private javax.swing.JTabbedPane jtpEditor;
    private javax.swing.JTextArea jtxtOuputLista;
    private javax.swing.JTextArea jtxtOuputPista;
    private javax.swing.JMenuItem mItemSave;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu munuAyuda;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
